### PR TITLE
talent: add engineering roles and career development

### PR DESCRIPTION
**Pull request by smola**
Add a guide with every engineering role, as well as how career development
and promotions work.

Signed-off-by: Santiago M. Mola <santi@mola.io>

### CODE REVIEW

**Comment by eiso** [comment]
My main

**Comment by eiso** [comment]
Overall this is goodn here is the comment that a Team Lead is a senior engineer II + management skills. It doesn't go in line with individual contributor progression. Since the gap between SE II and Expert is currently very high (salary wise).

Also SE I is well described but for SE II and Expert we just state more in depth knowledge, it's too vague.

**Comment by eiso** [comment]
Overall this is good but I have a few concerns. 

Currently a Team Lead is a senior engineer II + management skills. This doesn't go in line with individual contributor progression. Since the gap between SE II and Expert is currently very high (salary wise). 

Also SE I is well described but for SE II and Expert we just state more in depth knowledge, it's too vague.

Possible solutions are too add examples between SE I, II and Expert. These need to be more fine grained. I also think due to the salary difference between SE II and Expert there should be an SE III level.

**Comment by smola** [comment]
@eiso I agree that adding SE III makes sense, although to the best of my knowledge, that category does not exist as of today.

**Comment by smola** [comment]
@tsolakoua Added a sentence about hiring on Team Lead.

**Comment by juanjux** [comment]
On many companies, there is also the figure of "Principal Developer" (btw that was my role at my previous company). This is usually a role over the maximum seniority which implies somebody very experienced. It's not a manager, but keeps an eye on the other developers following good practices and conventions and sometimes writing guides related to those aspects. Probably this isn't needed here since we're still few and @smola and @mcuadros can do that aspect of the principal role, but it's something that could be considered in the future if we grow above the multitasking skills of them.

**Comment by smola** [comment]
@juanjux Note that _Expert Engineer_ is the maximum individual contributor level and it is analogous to _Principal Developer_ in some other places. As @eiso says, further levels might be introduced between _Senior II_ and _Expert_.

**Pull request merged**
