### PR TITLE
developer-community: update event list

### PR DESCRIPTION
**Pull request by bzz**
The list of events, past and upcoming is a bit stale, this brings

 - [x] AIFORSE
 - [x] FOSDEM2018
 - [x] South Summit
 - [x] Open Source Summit Europe

initiatives here. 

Looking forward a better maintained list of upcoming/past event materials in the future, since @campoy joined! 🚀

### CODE REVIEW

**Comment by marnovo** [comment]
@bzz can you please add to Oct:

As 1st item:
`| South Summit | Madrid | Speakers 🚀  | The Future of AI on Code |`

As last item: 
`| Open Source Summit Europe | Prague | Speakers 🚀 | Stack + Licensing App |`

**Comment by bzz** [comment]
@marnovo addressed in 7f13bad

@campoy thanks for prompt review!

**Comment by bzz** [comment]
🤦‍♂️ apparently, do not have rights to merge things in here. 

Would really appreciate a hand!

\cc @jorgeschnura

**Comment by campoy** [comment]
I don't have the rights either, unfortunately

**Pull request merged**
