### PR TITLE
Update licensing.md

### PR DESCRIPTION
**Pull request by bzz**
- [x] fixing a typo
 - [x] add note on re-licensing between src-d projects
 - [x] update wording for Apache/GPL licensing guide for projects, as [decided on retrospective](https://github.com/src-d/minutes/pull/35/files#diff-89b474f52e6f6b530e7dca2e343dcb64R29)

### CODE REVIEW

**Comment by bzz** [comment]
\cc @mcuadros for quick review

**Comment by bzz** [comment]
- 4a9ece3 proposes a notice on re-licensing between src-d projects
 - 52fd508 proposes some clarification to Apache vs GPL licensing

@smola @mcuadros please let me know what you think! 
Would be happy to incorporate any suggestions.

**Comment by eiso** [comment]
LGTM

**Comment by bzz** [comment]
Thanks for the prompt reviews @eiso @abeaumont !

**Comment by bzz** [comment]
friendly 1 week ping

@mcuadros is there anything you want to change/improve here?

**Comment by bzz** [comment]
@mcuadros if no objections, going to merge this wording update.

**Pull request merged**
