### PR TITLE
engineering: clarify OS/arch support

### PR DESCRIPTION
**Pull request by smola**
We support:

* Linux/amd64
* macOS/amd64
* Windows/amd64

Signed-off-by: Santiago M. Mola <santi@mola.io>

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
Which version of Windows? E.g. 7 is more painful than 10. Do we support building C/C++ projects with Visual Studio/MSC++ compiler?

macOS which version?

Linux which distros? Ubuntu 14.04? CentOS 6? Alternatively, which combinations of kernel+libc?

**Comment by smola** [comment]
@vmarkovtsev None of that is defined yet, but it is now a good moment to start the discussion. Here are some thoughts, not meant to be comprehensive. Also, your opinion is particularly welcome, since you're maintaining projects in multiple languages.

## Versions

I think we should try to commit ourselves to support recent versions (e.g. Windows 10, macOS 10.12/10.13, Ubuntu Linux 16.04/18.04). At least, in terms of what we actually test. On Linux we might want to target a broader variety of versions.

I don't think we have any particular interest in spending significant effort upfront in testing and supporting any CentOS, older Ubuntu versions, etc, but if there is demand in the community we will definitely accept patches and we might also put some effort ourselves too.

## C/C++ toolchains

So far I think we're supporting MSVC++ everywhere ([libuast](https://github.com/bblfsh/libuast/blob/master/WINDOWS.md), [lapjv](https://github.com/src-d/lapjv)...). I have no idea about our CUDA projects, so your input will be very valuable here.

For applications, I don't think we should commit to support any particular set of toolchains, if the project can be built on our target operating systems with whatever toolchains we say we support on our README, that should be ok.

For libraries, we probably want to support a wider range of toolchains (e.g. MinGW and MSVC++ on Windows, gcc or clang on Linux).

**Comment by smola** [comment]
@vmarkovtsev Any thought on this?

I'm thinking about rewording as:

> We actively test our projects on Ubuntu 14.04, macOS 10.13 and Windows 10 on amd64. We will gladly accept issues for other recent Linux, macOS and Windows. Support for other operating systems and architectures will require some help from the community.

> For the support of specific language compilers and runtimes, please refer to each language-specific guide. In the absence of it, we do our best to support a wide range of toolchains (e.g. `clang`, `gcc`, `msvc++`) in our libraries.

**Comment by vmarkovtsev** [comment]
Here is what happens with ML projects.

* Ubuntu 16.04 and 18.04 are supported (two most recent LTS versions). There is 14.04 in Travis but the critical things are installed through apt addons. It is a pain to support vanilla 14.04 for us.

* macOS most recent version. macOS is rather stable itself so most of the problems actually came from `brew` updates.

* Windows 10. Modern Windows lives rolling updated so it is hard to require any specific version. I would say those which were issued since the last year?

* amd64

* Python: 3.5+

* R 3.2.0+ - this is for the bindings to libs

* GCC 4.9+ - this implies full C++14 support and OpenMP 4

* clang 3.4+ - this implies full C++14 support

* msvc++ 2017 15.2+. - this implies full C++14 support

* Two most recent major CUDA versions, currently 8+

* GPU compute capability 6.1+

**Comment by smola** [comment]
@vmarkovtsev The runtime and build requirements should be documented explicitly in the README of each project.

I'm talking about this:

> Python: 3.5+
> R 3.2.0+ - this is for the bindings to libs
> GCC 4.9+ - this implies full C++14 support and OpenMP 4
> clang 3.4+ - this implies full C++14 support
> msvc++ 2017 15.2+. - this implies full C++14 support
> Two most recent major CUDA versions, currently 8+
> GPU compute capability 6.1+

Note that from the point of view of this guide, we should care more about runtime requirements, rather than build requirements. Also, requiring people to install additional stuff is acceptable too.

**Comment by vmarkovtsev** [comment]
The following are runtime requirements:
- Python
- R
- msvc++ - stdlib is not preinstalled by default and depends on the compiler version
- CUDA (libcuda.so, cudart is linked statically)
- Device compute capability

**Comment by smola** [comment]
@vmarkovtsev Would this sound good?

> We support Linux, macOS and Windows on amd64. Support for other operating systems and architectures will require some help from the community. Expect support for, at least, two latest Ubuntu LTS releases, two latest macOS releases and latest Windows and Windows Server releases.

> Some projects might define both build and runtime requirements that go beyond what is available by default on each operating system. Please, check the `README` of the project to know more about its requirements.

In short: at the moment we just refer to each project for their requirements, without any particular support policy globally set (yet). Requiring a recent GCC version is ok, it can be installed from a PPA or run in Docker in the worst case.

**Comment by vmarkovtsev** [comment]
OK

**Comment by smola** [comment]
@mcuadros ping?

**Pull request merged**
