### PR TITLE
update Applications offers

### PR DESCRIPTION
**Pull request by smola**
- Added more details about maintained projects.
- Removed Tensorflow mention.
- Clear explanation about required skills (e.g. programming languages).

### CODE REVIEW

**Comment by se7entyse7en** [comment]
> Scala coding skills and knowledge about Apache Spark aren't required but will be highly appreciated.

By reading this it seems that Scala is the main language of the stack maintained by the Apps team. Actually, when I joined I didn't even know Go, but yes I'm not a Senior and the offer is for Senior role. I mean that if we don't require even knowing Go we should say that too.

**Comment by carlosms** [comment]
I agree with @se7entyse7en's comment and https://github.com/src-d/guide/pull/336#discussion_r268707464, we should mention Go and not only Scala. Also I'm thinking we could drop the mention of Spark and replace it with something about frontend code.

Something similar to this:

> You will be expected to have strong backend coding skills in at least two languages, and very good algorithmic problem-solving skills. Skill at programming in Go, JavaScript, and Scala, and knowledge about single-page applications, are not required but will be highly appreciated. For Go in particular we strongly believe it can be learned by any skilled developer, and we care much more about our team's mindset and prior experience than specific language skills.

**Comment by carlosms** [comment]
I was thinking we could add the technologies used in each project. But now that I see it maybe it adds noise, and the repo link is enough...

> Some of the projects the Application Team maintains are:
> 
> - [engine](https://github.com/src-d/engine/): a simple interface to our Code as Data stack based on Docker. (_Go_)
> - [lookout](https://github.com/src-d/lookout/): a platform for Assisted Code Review. (_Go_)
> - [gemini](https://github.com/src-d/gemini/): duplicated code detection at scale. (_Scala_, _Spark_, _python_)
> - [gitbase-web](https://github.com/src-d/gitbase-web) and [bblfsh/web](https://github.com/bblfsh/web): web interfaces for some of our projects. (_JS_, _React_, _Go_)

**Comment by smola** [comment]
Merging, although it needs further updates now.

**Pull request merged**
