### PR TITLE
Added language analysis job description

### PR DESCRIPTION
**Pull request by juanjux**
Adds the job description for the Language Analysis team.

Signed-off-by: Juanjo Alvarez <juanjo@sourced.tech>

### CODE REVIEW

**Comment by tsolakoua** [comment]
@juanjux thanks for the PR! Could you please add also to the file the text from here? https://jobs.lever.co/sourced/0b200e00-7798-4aa1-a046-a216a9144ded
And what you wrote should be in the "Role".
In that way we will have the whole description as it will be shown in our website.

**Comment by juanjux** [comment]
@tsolakoua done!

**Comment by juanjux** [comment]
@eiso you should probably update the other job descriptions then, that part outside of the role is copypasted from them.

**Comment by tsolakoua** [comment]
@juanjux I'll update the parts outside the role for the other descriptions on Lever with the changes of @eiso.

**Pull request merged**
