### PR TITLE
general: Party recovery clarification

### PR DESCRIPTION
**Pull request by mcuadros**

### CODE REVIEW

**Comment by mcuadros** [comment]
I related with the fact that is required, if you don't get drunk or you didn't arrive late, I don't see why is required to have a free day.

**Comment by eiso** [comment]
My 2 cents:

I personally believe that we should **definitely not** ever have anyone feel that it is encouraged by the company to drink alcohol or stay late (also what is late in Spain anyways?). That would be the opposite of making people feel included in what is to be a **celebration for everyone**. 

A free day (or starting later) is not rewarding or smoothing because someone is either not feeling well or is sleeping throughout Friday, which we say is okay, and it should be. If people want to celebrate late or with alcohol and we hold this on a Thursday it would be cruel to make everyone show up at 9am the next day. 

IMHO we should adjust the language to be reflect the above and add something like "if you feel up for it, we'd love to see you in the office on Friday, if you don't, no worries, come in later or stay at home".

**Comment by mcuadros** [comment]
I just updated the PR  with the Eiso's comment. I really thing that is a much better way to express what I wanted.

**Comment by alcortesm** [comment]
The current text address all my concerns expressed here completely.

Sadly it is missing the point we raised a few weeks ago which was: is this text talking about working on remote or not working at all?

Can you clarify this last point, please?

**Pull request merged**
