### PR TITLE
update organizational chart as per Aug 27 2019

### PR DESCRIPTION
**Pull request by gomesfernanda**
Covers:
- [Issue 374](https://github.com/src-d/guide/issues/374)
- [Issue 158](https://github.com/src-d/office/issues/158)
- [Issue 157](https://github.com/src-d/office/issues/157)

Signed-off-by: Fernanda Gomes <fergomes@gmail.com>

### CODE REVIEW

**Comment by ncordon** [comment]
This is extremely nitpicking (feel free to ignore it :smile: ): it is Alejandro García (now it is written without accent as Garcia). I have not seen any other accents off though

**Comment by agarciamontoro** [comment]
Also, it should read "Data Processing Jr Eng".

**Comment by gomesfernanda** [comment]
@bluer73 should I change to Jr? We had talked about Eng...

**Comment by agarciamontoro** [comment]
I just talked to @ajnavarro and it seems that both @ncordon and I are offiicially Engineer I, so I guess that it is @ncordon's title the one that needs a change (?) Yesterday I noticed that we had different ranks, and I just assumed that the wrong one was mine, sorry for the noise.

**Comment by ncordon** [comment]
> I just talked to @ajnavarro and it seems that both @ncordon and I are offiicially Engineer I, so I guess that it is @ncordon's title the one that needs a change (?) Yesterday I noticed that we had different ranks, and I just assumed that the wrong one was mine, sorry for the noise.

I do not know what I am officialy so I can be jr in the chart or whatever. My accent in Cordón looks good though :rofl:

**Comment by gomesfernanda** [comment]
Fixed Nacho's role and Alejandro's surname

**Comment by vcoisne** [comment]
@gomesfernanda Nicholas's internship is over. In general, I would recommend not including interns in org charts.

**Comment by gomesfernanda** [comment]
Removed Nicholas on this 3rd commit

**Pull request merged**
