### PR TITLE
talent: add table with precalculated stock options

### LINKED ISSUE #252: Add table of precalculated stock options for each team and role
Applying the formula everytime is tedious and error prone, it would be good to have a table with all current values precalculated.

### PR DESCRIPTION
**Pull request by smola**
fixes #252 

Generated with script:

```python
#!/usr/bin/env python

teams=[
        ('Data Science', 0.12),
        ('Developer Community', 0.12),
        ('Engineering', 0.1),
        ('Product', 0.1),
        ('Operations', 0.05)
]

stages=[
        ('Seed', 2.0),
        ('Series A', 4.0)
]

roles=[
        ('VP', 0.37),
        ('Lead', 0.17),
        ('Senior', 0.07),
        ('Normal', 0.02),
        ('Junior', 0.00)
]

total = 24394

def get_options(team, stage, role, total):
        return round((team/stage+role)/100*total)

stage_title = 'Series A'
stage_val = dict(stages)[stage_title]
for team_title, team_val in teams:
        for role_title, role_val in roles:
                options = get_options(team_val, stage_val, role_val, total)
                print('%s | %s | %d' % (team_title, role_title, options))
```

### CODE REVIEW

**Comment by tsolakoua** [comment]
Thanks @smola, we indeed needed it!! 
stage_title = 'Seed' should be stage_title = 'Series A'

**Comment by smola** [comment]
@tsolakoua Fixed, thanks!

**Comment by marnovo** [comment]
Q: Is the "head" level the same as "lead" or as "VP"?

**Comment by smola** [comment]
@marnovo In terms of stock options, I think lead, but :man_shrugging:

**Comment by marnovo** [comment]
@smola answered/fixed by https://github.com/src-d/guide/commit/9bb36ec93d5b1ef0a51b10bddf6c47e1211bab7f

**Pull request merged**
