### PR TITLE
Add ML extras to the grades

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Motivation: it is hard for the ML team members to understand the detailed requirements for each role.
E.g. we do not design new features - we solve data science problems and work on the ML algorithms.
A "feature" in our vocabulary is a property of the input data :-D

### CODE REVIEW

**Comment by tsolakoua** [comment]
@vmarkovtsev By reading the extras, if I was an outside-source{d} person I would feel that the work being done is only research-oriented with focus on papers, which doesn't reflect the real ML work.

**Comment by vmarkovtsev** [comment]
ML is indeed research-oriented with the focus on the papers at source{d} :) E.g. let's consider the format style analyzer. We are creating it from scratch, there is no prior research, we had to read tens of papers on the related topics and listen/speak to many academics to understand what to actually do. When and if that project succeeds, it will be a walking paper to write (if there is time ofc!).

The future plans about best practices are even crazier and we will have to do research from scratch again simply because nobody in the world has worked with gigabytes of structured diffs.

**Comment by vmarkovtsev** [comment]
@mcuadros What if I try to format as a table? There can be rows for grades, one column with general requirements, extra columns for teams.

Another idea: hide those under spoilers.

Engineer I: blah-blah.
<details>
  <summary>ML clarifications</summary>
You are expected to write 100500 papers! 
</details>

**Comment by vmarkovtsev** [comment]
After discussing IRL: I will reformat this as an Appendix.

**Comment by vmarkovtsev** [comment]
@mcuadros Done with appendix, PTAL

**Comment by vmarkovtsev** [comment]
@mcuadros Friendly 1 month ping

**Pull request merged**
